export const GET_WEATHER_REQUEST = 'GET_WEATHER_REQUEST'
export const GET_WEATHER_SUCCESS = 'GET_WEATHER_SUCCESS'
export const GET_WEATHER_ERROR = 'GET_WEATHER_ERROR'

export const GET_DETAILS_WEATHER_REQUEST = 'GET_DETAILS_WEATHER_REQUEST'
export const GET_DETAILS_WEATHER_SUCCESS = 'GET_DETAILS_WEATHER_SUCCESS'
export const GET_DETAILS_WEATHER_ERROR = 'GET_DETAILS_WEATHER_ERROR'
